<div style="background-color: #21409A; color: white; font-size: 15px; padding: 10px; margin-bottom: 2px; display: flex">
    <div style="margin-right: 15px;
        display: flex;
        flex-direction: column;
        justify-content: center;">
        <img src="<?php echo $this->getViewFileUrl('Vexpro_Autenticacao::img/ico_seeds.png'); ?>" />
    </div>
    <div>
        Saldo <span style="font-weight: bold;">Pontuação</span><br /><?php echo $block->pointsConsumer(); ?>
    </div>
</div>

<div style="background-color: #21409A; color: white; font-size: 15px; padding: 10px; display: flex">
    <div style="margin-right: 15px;
        display: flex;
        flex-direction: column;
        justify-content: center;">
        <img src="<?php echo $this->getViewFileUrl('Vexpro_Autenticacao::img/ico_carteiraDigital.png'); ?>" />
    </div>
    <div>
        Saldo <span style="font-weight: bold;">Carteira digital</span><br /><?php echo $block->walletConsumer(); ?>
    </div>
</div>
