<?php

/** @var \Vexpro\Autenticacao\Block\Template $block */
?>

<style>
    .MyButton {
        background: #3DBAC7;
        color: white;
        padding: 15px;
        border-radius: 6px;
    }

    .modal-footer {
        display: flex;
        justify-content: center;
    }

    .template {
        display: flex;
        justify-content: center;
    }

    .modal-popup.modal-slide .modal-footer {
        border-top: none;
    }

    .MyAlert {
        padding: 15px;
        background: #ecad00;
        color: white;
        margin-bottom: 15px;
        width: 100%;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .conteudo {
        display: flex;
        align-items: center;
        justify-content: flex-start;
    }
</style>

<div class="template">


    <?php
    $flag_change_email = 0;
    if (isset($block->getRequest()->getParams()['change_email'])) {
        $flag_change_email = 1;
    }
    $used_email = "";
    if (isset($block->getRequest()->getParams()['used_email'])) {
        $used_email = trim($block->getRequest()->getParams()['used_email'], "/");
    }
    ?>

    <?php if ($flag_change_email == 1) { ?>

        <div class='MyAlert'>
            <div class='conteudo'>
                <img style="margin-right: 20px" src="<?php echo $this->getViewFileUrl('Vexpro_Autenticacao::img/ico_atencao.png'); ?>" />
                <div style="display: flex; flex-direction: column">
                    <div style="font-weight: bold;">E-MAIL INVÁLIDO</div>
                    <spam>O e-mail <?php echo $used_email; ?> já foi utilizado. Você deve utilizar outro e-mail para concluir o cadastro.</spam>

                </div>
            </div>
            <img id='fechar' style="height: 20px; cursor: pointer;" src="<?php echo $this->getViewFileUrl('Vexpro_Autenticacao::img/fechar_aviso.png'); ?>" />
        </div>
    <?php } ?>

    <?php if ($block->fidelity() == 2) { ?>
        <div class='MyAlert'>
            <div class='conteudo'>
                <img style="margin-right: 20px" src="<?php echo $this->getViewFileUrl('Vexpro_Autenticacao::img/ico_atencao.png'); ?>" />
                <div style="display: flex; flex-direction: column">
                    <spam>Você ainda não concluiu seu cadastro no Programa de fidelidade. Acesse o programa e informe seu login / senha utilizados na loja para validar seu cadastro.</spam>
                    <div><a href="#" id="conheca" style="color: white;">SAIBA MAIS</a></div>
                </div>
            </div>
            <img id='fechar' style="height: 20px; cursor: pointer;" src="<?php echo $this->getViewFileUrl('Vexpro_Autenticacao::img/fechar_aviso.png'); ?>" />
        </div>

    <?php } else if ($block->fidelity() == 0) { ?>

        <div class='MyAlert'>
            <div class='conteudo'>
                <img style="margin-right: 20px" src="<?php echo $this->getViewFileUrl('Vexpro_Autenticacao::img/ico_atencao.png'); ?>" />
                <div style="display: flex; flex-direction: column">
                    <spam>Você ainda não possui cadastro no programa de fidelidade.</spam>
                    <div><a href="#" id="conheca2" style="color: white;">Conheça o programa</a></div>
                </div>
            </div>
            <img id='fechar' style="height: 20px; cursor: pointer;" src="<?php echo $this->getViewFileUrl('Vexpro_Autenticacao::img/fechar_aviso.png'); ?>" />
        </div>
    <?php } ?>

    <!--MODAL CONHECA-->
    <div id="modal-conheca" style="display:none">
        <div class="modal-inner-content">
            <p>O Programa C.Vale Fidelidade, nasceu para valorizar você que é nosso cliente. Com nossa "moeda" Seed
                (SD$) você estará em casa para comprar produtos de excelente qualidade e ainda acumular pontos.</p>

            <p>C.Vale Fidelidade está disponível em nossa rede de Supermercados, Hipermercados e Posto de combustível.
                Você acumula pontos e tem a oportunidade de trocar por produtos em promoções especiais.</p>


            <p>Para participar basta realizar o cadastro no programa C.Vale Fidelidade e identificar suas compras em
                nossas lojas indicando seu CPF no momento da emissão do cupom fiscal. Caso você não tenha se
                identificado nos cupons de compra, abra nosso aplicativo ou site e vincule seus pontos através da
                leitura do QR Code do seu cupom.</p>


            <p>Você acumula nos produtos identificados e em nossas campanhas exclusivas.</p>

            <p>Venha acumular Seeds, aproveite!</p>
        </div>
    </div>
    <div id="modal-conheca2" style="display:none">
        <div class="modal-inner-content">
            <p>O Programa C.Vale Fidelidade, nasceu para valorizar você que é nosso cliente. Com nossa "moeda" Seed
                (SD$) você estará em casa para comprar produtos de excelente qualidade e ainda acumular pontos.</p>

            <p>C.Vale Fidelidade está disponível em nossa rede de Supermercados, Hipermercados e Posto de combustível.
                Você acumula pontos e tem a oportunidade de trocar por produtos em promoções especiais.</p>


            <p>Para participar basta realizar o cadastro no programa C.Vale Fidelidade e identificar suas compras em
                nossas lojas indicando seu CPF no momento da emissão do cupom fiscal. Caso você não tenha se
                identificado nos cupons de compra, abra nosso aplicativo ou site e vincule seus pontos através da
                leitura do QR Code do seu cupom.</p>


            <p>Você acumula nos produtos identificados e em nossas campanhas exclusivas.</p>

            <p>Venha acumular Seeds, aproveite!</p>
        </div>
    </div>
</div>



<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal',
        'redirectUrl',
        'mage/mage',
        'mage/calendar',
        'jquery.mask',
        'loader'
    ], function($, modal) {

        $(document).ready(function() {

            var options = {
                innerScroll: true,
                type: 'popup',
                responsive: true,
                title: 'O QUE É O C.VALE FIDELIDADE?',
                buttons: [{
                    text: $.mage.__('ACESSAR O PROGRAMA DE FIDELIDADE'),
                    class: 'MyButton',
                    click: function() {
                        window.open('<?php echo $block->baseUrl() . "/auth/login" ?>');
                    }
                }]
            };
            var options2 = {
                innerScroll: true,
                type: 'popup',
                responsive: true,
                title: 'O QUE É O C.VALE FIDELIDADE?',
                buttons: [{
                    text: $.mage.__('ACESSAR O PROGRAMA DE FIDELIDADE'),
                    class: 'MyButton',
                    click: function() {
                        window.open('<?php echo $block->baseUrl() . "/register" ?>');
                    }
                }]
            };

            modal(options, $('#modal-conheca'));
            modal(options2, $('#modal-conheca2'));

            $("#conheca").click(function() {
                $("#modal-conheca").modal("openModal");
            })
            $("#conheca2").click(function() {
                $("#modal-conheca2").modal("openModal");
            })

            $("#fechar").click(function() {
                // $(".MyAlert").hide()
                $(".MyAlert").fadeOut(500);
            })

        })


    })
</script>