<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Framework\View\Element\Template $block */
?>
<?= $block->escapeHtml(__('Você ainda não concluiu seu cadastro no Programa de fidelidade. Acesse o programa e informe seu login / senha utilizados na loja para validar seu cadastro. <a href="%1" id="conheca">Clique Aqui</a>.', '#'), ['a']);?>
