<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Registered Customers')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="login-form">
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <div class="field note"><?= $block->escapeHtml(__('Caso tenha uma conta entre com o seu CPF')) ?></div>

                <div class="field cpf required">
                    <label class="label" for="cpf"><span><?= $block->escapeHtml(__('CPF')) ?></span></label>
                    <div class="control">

                        <div class="control">
                            <input type="text" id="cpf" name="login[username]" value="<?php if (isset($block->getRequest()->getParams()['cpf'])) {
                                                                                            echo $block->getRequest()->getParams()['cpf'];
                                                                                        }
                                                                                        ?>" title="<?php /* @escapeNotVerified */ echo __('CPF') ?>" class="input-text" data-validate="{required:<?php echo var_export($block->getStatus("required", "cpf", "cpf"), true) ?>, 'validate-cpf':true}">
                        </div>

                    </div>
                </div>

                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off" <?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                    <div class="secondary"><a class="action remind" href="<?=

                                                                            $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                </div>
            </fieldset>
        </form>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "[data-role=type-individual], [data-role=type-corporation]": {
            "changePersonType" : {
                "changeFirstnameLabel": <?php echo ($block->getConfigAdmin("cnpj", "copy_firstname") ? "true" : "false"); ?>,
                "changeLastnameLabel": <?php echo ($block->getConfigAdmin("cnpj", "copy_lastname") ? "true" : "false"); ?>
            }
        }
    }
</script>

<script>
    require([
        'jquery',
        'inputMask'
    ], function($) {
        $('#cpf').mask('000.000.000-00', {
            clearIfNotMatch: true
        });
        $('#cnpj').mask('00.000.000/0000-00', {
            clearIfNotMatch: true
        });
    });
</script>
