<style>
    #policy {
        cursor: pointer;
        color: #21409A;
        font-style: normal;
        text-decoration: underline;
    }

    .search {
        position: relative;
        color: #aaa;
        font-size: 16px;
    }

    .search {}

    .search input {}

    .search input {}

    .search .fa-search {
        position: absolute;
        left: 10px;
        top: 5px;
    }

    .search .fa-search {
        left: auto;
        right: 10px;
    }


    .input-icons {
        width: 100%;
        margin-bottom: 10px;
    }

    .icon {
        padding: 10px;

    }

    .input-field {
        width: 100%;
        padding: 10px;
        padding-right: 50px;
        text-align: left;
    }

    .loading-mask .loader>p {
        display: block;
        font-size: large;
    }

    .nav-sections {
        margin-bottom: 0px !important;
    }

    .vl {
        border-left: 2px solid #444444;
        height: 100%;
        margin-right: 20px;
    }

    a {
        color: #21409A;
    }

    .modal-inner-content {
        line-height: 20px;
    }

    ul>li,
    ol>li {
        margin-top: 0rem;
        margin-bottom: 0px !important;
    }

    :root {
        --num-of-grid-columns: 6;
    }

    form {
        width: 100% !important;
    }

    .counteudo {
        display: grid;
        background: #f8f8f8 !important;
        grid-template-columns: repeat(var(--num-of-grid-columns), 1fr);
        grid-gap: 20px;
        grid-template-areas:
            "cpf_field nome1 nome2 nome2 nasc genero"
            "email email email email celular telefone"
            "cep endereco endereco endereco numero complemento"
            "bairro cidade uf pais . ."
            "senha senha conf_senha conf_senha . ."
    }

    @media screen and (max-width: 768px) {
        :root {
            --num-of-grid-columns: 1;
        }

        .counteudo {
            display: grid;
            background: #f8f8f8 !important;
            grid-template-columns: repeat(var(--num-of-grid-columns), 1fr);
            grid-gap: 30px;
            grid-template-areas: "cpf_field"
                "nome1"
                "nome2"
                "nasc"
                "genero"
                "email"
                "celular"
                "telefone"
                "cep"
                "endereco"
                "numero"
                "complemento"
                "bairro"
                "cidade"
                "uf"
                "pais"
                "senha"
                "conf_senha"
        }
    }

    #cpf_field {
        grid-area: cpf_field;
    }

    #firstname_field {
        grid-area: nome1;
    }

    #lastname_field {
        grid-area: nome2;
    }

    #nasc_field {
        grid-area: nasc;
    }

    #gender_field {
        grid-area: genero;
    }

    #email_field {
        grid-area: email;
    }

    #phone_field {
        grid-area: celular;
    }

    #phone_field2 {
        grid-area: telefone;
    }

    #zip_field {
        grid-area: cep;
    }

    #address_field {
        grid-area: endereco;
    }

    #number_field {
        grid-area: numero;
    }

    #complement_field {
        grid-area: complemento;
    }

    #bairro_field {
        grid-area: bairro;
    }


    #city_field {
        grid-area: cidade;
    }

    #uf_field {
        grid-area: uf;
    }

    #pais_field {
        grid-area: pais;
    }

    #password_field {
        grid-area: senha;
    }

    #password_field2 {
        grid-area: conf_senha;
    }

    .label {
        width: auto !important;
    }

    .modal-inner-wrap {
        border-radius: 8px;
    }

    #box {
        padding: 20px;
        background: #fff;
        border-radius: 10px;
        margin-top: 20px;
        height: 100px;
        display: flex;
        width: 800px;
    }

    #left {
        height: 100%;
        width: 30%;
        display: flex;
        justify-content: left;
        align-items: center;
        font-weight: bold;
    }

    #right {
        height: 100%;
        width: 70%;
        display: flex;
        justify-content: center;
        align-items: start;
        flex-direction: column;
    }

    .loading-mask-custom2 {
        position: absolute;
        top: 50%;
        left: 50%;
        background: rgba(0, 0, 0, 0.6);
        z-index: 2;
        width: 600px;
        transform: translate(-50%, -50%);
        height: 200px;
        color: #fff;
        font-size: large;
        border-radius: 20px;
    }

    .tooltip {
        display: inline-block;
        position: relative;
        text-align: left;
    }

    .tooltip h3 {
        margin: 12px 0;
    }

    .tooltip .top {
        min-width: 300px;
        max-width: 400px;
        top: -20px;
        left: 50%;
        transform: translate(-30%, -100%);
        padding: 10px 20px;
        color: #ffffff;
        background-color: #444444;
        font-weight: normal;
        font-size: 14px;
        border-radius: 8px;
        position: absolute;
        z-index: 99999999;
        box-sizing: border-box;
        box-shadow: 0 1px 8px rgba(0, 0, 0, 0.5);
        display: none;
    }

    .tooltip:hover .top {
        display: block;
    }

    .tooltip .top i {
        position: absolute;
        top: 100%;
        left: 30%;
        margin-left: -15px;
        width: 30px;
        height: 15px;
        overflow: hidden;
    }

    .tooltip .top i::after {
        content: '';
        position: absolute;
        width: 15px;
        height: 15px;
        left: 50%;
        transform: translate(-50%, -50%) rotate(45deg);
        background-color: #444444;
        box-shadow: 0 1px 8px rgba(0, 0, 0, 0.5);
    }



    .tooltip h3 {
        margin: 12px 0;
    }


    .tooltip .text-content {
        padding: 10px 20px;
    }

    .tooltip .right {
        min-width: 350px;
        max-width: 400px;
        top: 50%;
        left: 100%;
        margin-left: 20px;
        transform: translate(0, -50%);
        padding: 0;
        color: #EEEEEE;
        background-color: #444444;
        font-weight: normal;
        font-size: 13px;
        border-radius: 8px;
        position: absolute;
        z-index: 99999999;
        box-sizing: border-box;
        box-shadow: 0 1px 8px rgba(0, 0, 0, 0.5);
        visibility: hidden;
        opacity: 0;
        transition: opacity 0.8s;
    }

    .tooltip:hover .right {
        visibility: visible;
        opacity: 1;
    }

    .tooltip .right img {
        width: 400px;
        border-radius: 8px 8px 0 0;
    }

    .tooltip .text-content {
        padding: 10px 20px;
    }

    .tooltip .right i {
        position: absolute;
        top: 50%;
        right: 100%;
        margin-top: -12px;
        width: 12px;
        height: 24px;
        overflow: hidden;
    }

    .tooltip .right i::after {
        content: '';
        position: absolute;
        width: 12px;
        height: 12px;
        left: 0;
        top: 50%;
        transform: translate(50%, -50%) rotate(-45deg);
        background-color: #444444;
        box-shadow: 0 1px 8px rgba(0, 0, 0, 0.5);
    }
</style>

<?php echo $block->getChildHtml('form_fields_before') ?>
<?php /* Extensions placeholder */ ?>
<?php echo $block->getChildHtml('customer.form.register.extra') ?>

<form class="form create account form-create-account" action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off" data-mage-init='{"validation": {}}'>
    <?php echo $block->getBlockHtml('formkey'); ?>

    <div class="counteudo">

        <div id="cpf_field">
            <div class="field fieldset individual" style="display: flex;
    align-items: center;">
                <div class="field required">
                    <label for="cpf" class="label">CPF</label>
                    <div>
                        <input type="text" id="cpf" name="cpf" value="" title="CPF" class="input-text" data-validate='{"required":true}' autocomplete="off" aria-required="true" style="min-width: 270px;">
                    </div>
                </div>

                <div class="tooltip">
                    <img style="margin-right: 20px" src="<?php echo $this->getViewFileUrl('Vexpro_Autenticacao::img/info-circle-solid.png'); ?>" />
                    <div class="top">
                        <span style="font-size: 12px">Esse dado será usado no login do sistema.</span>
                        <i></i>
                    </div>
                </div>

            </div>
        </div>

        <div id="firstname_field">
            <div class="field fieldset individual">
                <div class="field required">
                    <label for="firstname" class="label">Nome</label>
                    <input id="firstname" name="firstname" type="text" class="input-text required-entry" data-validate="{required:true}" aria-required="true" />
                </div>
            </div>
        </div>
        <div id="lastname_field">
            <div class="field fieldset individual">
                <div class="field required">
                    <label for="lastname" class="label">Sobrenome</label>
                    <input name="lastname" type="text" id="lastname" class="input-text required-entry" data-validate="{required:true}" aria-required="true" />
                </div>
            </div>
        </div>
        <div id="nasc_field">
            <div class="field fieldset individual">
                <div class="field required">
                    <label for="dob" class="label">Data de nasc.</label>
                    <input name="dob" id="dob" type="text" class="input-text required-entry" data-validate="{required:true}" aria-required="true" />
                </div>
            </div>
        </div>

        <div id="gender_field">
            <div class="field fieldset individual">
                <div class="field required">
                    <label for="gender" class="label">Gênero</label>
                    <select id="gender" name="gender" aria-required="true" validate-select="true">
                        <option value=""><?php /* @escapeNotVerified */ echo __('') ?></option>
                        <option value=1>Masculino</option>
                        <option value=2>Feminino</option>
                        <option value=3>Não informar</option>
                        <!-- <option value="n">Não informar</option> -->
                    </select>
                </div>
            </div>
        </div>
        <div id="email_field">
            <div class="field fieldset individual">
                <div class="field required">
                    <label for="email_address" class="label">Email</label>
                    <input type="email" name="email" autocomplete="email" id="email_address" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
                </div>
            </div>
        </div>
        <div id="phone_field">
            <div class="field fieldset individual">
                <div class="field required">
                    <label for="telephone" class="label">Celular</label>
                    <input name="telephone" type="text" id="telephone" class="input-text required-entry" data-validate="{required:true}" validate-phoneStrict aria-required="true" />
                </div>
            </div>
        </div>
        <div id="phone_field2">
            <div class="field fieldset individual">
                <div class="field">
                    <label for="telephone2" class="label">Telefone</label>
                    <input name="telephone2" id="telephone2" type="text" class="input-text" validate-phoneStrict />
                </div>
            </div>
        </div>
        <div id="zip_field">
            <div class="field fieldset individual">
                <div class="field required">
                    <label for="postcode" class="label">CEP</label>
                    <input id="postcode" name="postcode" type="text" class="input-text validate-zip-international required-entry" aria-required="true" />
                </div>
            </div>
        </div>
        <div id="address_field">
            <div class="field fieldset individual">
                <div class="field required">
                    <label for="street_1" class="label">Endereço</label>
                    <input name="street[0]" id="street_1" type="text" class="input-text required-entry" aria-required="true" />
                </div>
            </div>
        </div>
        <div id="number_field">
            <div class="field fieldset individual">
                <div class="field required">
                    <label for="street_2" class="label">Número</label>
                    <input name="street[1]" id="street_2" class="input-text required" type="text" />
                </div>
            </div>
        </div>
        <div id="complement_field">
            <div class="field fieldset individual">
                <div class="field">
                    <label for="complemento" class="label">Complemento</label>
                    <input name="complemento" max_length="20" id="complemento" type="text" class="input-text" />
                </div>
            </div>
        </div>
        <div id="bairro_field">
            <div class="field fieldset individual">
                <div class="field required">
                    <label for="street_3" class="label">Bairro</label>
                    <input name="street[2]" id="street_3" type="text" class="input-text required-entry" aria-required="true" />
                </div>
            </div>
        </div>
        <div id="city_field">
            <div class="field fieldset individual">
                <div class="field required">
                    <label for="city" class="label">Cidade</label>
                    <select name="city" id="city" class="required-entry" aria-required="true">
                        <option value="">
                        </option>
                    </select>
                </div>
            </div>
        </div>
        <div id="uf_field">
            <div class="field fieldset individual">
                <div class="field required">
                    <label for="region_id" class="label">UF</label>
                    <select id="region_id" name="region_id" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="validate-select" style="display:none;">
                        <option value="">
                            <?php /* @escapeNotVerified */ echo __('') ?>
                        </option>
                    </select>
                    <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>" style="display:none;">
                </div>
            </div>
        </div>
        <div id="pais_field">
            <div class="field fieldset individual">
                <div class="field required">
                    <label class="label">País</label>
                    <?php echo $block->getCountryHtmlSelect() ?>
                </div>
            </div>
        </div>
        <div id="password_field">
            <div class="field fieldset individual">
                <div class="field required">
                    <label for="password" class="label">Senha</label>

                    <div class="search">
                        <img style="height: 30px;" class="fa fa-search" id="toggle" src="<?php echo $this->getViewFileUrl('Vexpro_Autenticacao::img/eye-solid.png'); ?>" />
                        <input maxlength="20" data-validate="{required:true, germiniPassword:true, germiniPassword2:true,germiniPassword3:true,germiniPassword4:true}" type="password" name="password" validate-password id="password" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" class="input-text" autocomplete="off">
                    </div>

                </div>
            </div>
        </div>


        <div id="password_field2">
            <div class="field fieldset individual">
                <div class="field required">
                    <label for="password-confirmation" class="label">Confirmar senha</label>

                    <div class="search">
                        <img style="height: 30px;" class="fa fa-search" id="toggle2" src="<?php echo $this->getViewFileUrl('Vexpro_Autenticacao::img/eye-solid.png'); ?>" />
                        <input maxlength="20" type="password" name="password_confirmation" title="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                    </div>


                    <div style="float: right; margin-top: 5px">
                        <span style="color: #7E7E7E;">Políticas de senha</span>
                        <div class="tooltip">
                            <img style="margin-right: 20px" src="<?php echo $this->getViewFileUrl('Vexpro_Autenticacao::img/info-circle-solid.png'); ?>" />
                            <div class="right" style="padding-top: 5px;">
                                <span style="font-weight: bold; margin-left: 15px; margin-top: 15px; font-size: 12px;">Regras:</span>
                                <ul style="margin-left: -15px;">
                                    <li>No mínimo 8 caracteres</li>
                                    <li>Conter letras, números e caracteres especiais</li>
                                    <li>Não pode ter mais de 3 números sequenciais</li>
                                    <li>Não pode ter números repetidos em ordem</li>
                                    <li>Não ser igual ao CPF, CNPJ, data de nascimento, telefone ou celular.</li>
                                </ul>
                                <i></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

    <hr>
    <div id="policy_field">
        <div class="field choice" style="display: flex; align-items: center;">
            <div style="display: flex; align-items: baseline;">
                <input type="checkbox" name="change_policy" id="change_policy" value="1" class="checkbox" />
                <label for="change_policy" style="font-weight: bold" class="label"><span>Aceito as <i id="policy">Políticas de privacidade</i></span></label>
            </div>
        </div>
    </div>

    <hr>
    <div id="fidelidade_field">
        <div class="field choice" style="display: flex; align-items: center;">
            <div style="display: flex; align-items: baseline;">
                <input type="checkbox" name="is_fidelidade" id="is_fidelidade" title="<?php /* @escapeNotVerified */ echo __('Quero Participar do PROGRAMA DE FIDELIDADE') ?>" value="1" id="is_fidelidade" class="checkbox" />
                <label for="is_fidelidade" style="font-weight: bold" class="label"><span><?php /* @escapeNotVerified */ echo __('Quero Participar do PROGRAMA DE FIDELIDADE') ?></span></label>
            </div>

            <span style="margin-left: 1em; border-radius: 6px;background:#21409A;" id="conheca" class="action submit primary"><span>Conheça o C.VALE
                    FIDELIDADE</span></span>

        </div>
    </div>

    <div id="box">
        <div id="left">
            <div>
                <input type="checkbox" name="selecionar_todos" id="selecionar_todos" value="1" class="checkbox" />
                <span>Selecionar todos</span>
            </div>
        </div>
        <div class="vl"></div>
        <div id="right">
            <div>
                <input type="checkbox" name="aceito_termos_uso" id="aceito_termos_uso" value="1" class="checkbox" />
                <span>Aceito os <a id='tu' style="cursor: pointer;">Termos de Uso</a>.</span>
            </div>
            <div>
                <input type="checkbox" name="aceito_regulamento" id="aceito_regulamento" value="1" class="checkbox" />
                <span>Aceito o <a id='reg' style="cursor: pointer;">Regulamento do programa de fidelidade</a>.</span>
            </div>
            <div>
                <input type="checkbox" name="desejo_notificacao" id="desejo_notificacao" value="1" class="checkbox" />
                <span>Desejo receber notificação sobre o programa.</span>
            </div>

        </div>
    </div>



    <hr style="margin-bottom: 0px !important;">

    <?php echo $block->getChildHtml('form_additional_info'); ?>
    <input type="hidden" name="user_fidelidade" id="user_fidelidade" value="0" />
    <input type="hidden" name="create_address" value="1" />
    <input type="hidden" name="default_billing" value="1">
    <input type="hidden" name="default_shipping" value="1">

    <input type="hidden" id="associated" name="associated" value="0">

    <input type="hidden" id="policy_accepted" name="policy_accepted" value="0">

    <div>
        <div class="primary">
            <button type="submit" style="border-radius: 6px !important; margin-top: 20px;margin-bottom: 20px" class="action submit primary" id="button_create" title="<?php /* @escapeNotVerified */ echo __('Create an Account') ?>"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></button>
        </div>
    </div>

    <!--MODAL-->
    <div id="modal-termos">
        <div class="modal-inner-content" id="conteuto-termos">
        </div>
    </div>

    <!--MODAL-->
    <div id="modal-regulamentos">
        <div class="modal-inner-content" id="conteudo-regulamentos">
        </div>
    </div>

    <!--MODAL-->
    <div id="modal-content">
        <div class="modal-inner-content">
            <p>O CPF <span id="cpf_modal" style="color: #21409A;
    font-weight: bold;"></span> já está cadastrado no programa de fidelidade.<br />Você pode utilizar a mesma senha para acessar a loja da C.VALE.</p>
            <p><a target="_blank" href="/customer/account/forgotpassword/">ESQUECI A SENHA</a></p>
        </div>
    </div>

    <!--MODAL CONHECA-->
    <div id="modal-conheca">
        <div class="modal-inner-content">
            <p>O Programa C.Vale Fidelidade, nasceu para valorizar você que é nosso cliente. Com nossa "moeda" Seed
                (SD$) você estará em casa para comprar produtos de excelente qualidade e ainda acumular pontos.</p>

            <p>C.Vale Fidelidade está disponível em nossa rede de Supermercados, Hipermercados e Posto de combustível.
                Você acumula pontos e tem a oportunidade de trocar por produtos em promoções especiais.</p>


            <p>Para participar basta realizar o cadastro no programa C.Vale Fidelidade e identificar suas compras em
                nossas lojas indicando seu CPF no momento da emissão do cupom fiscal. Caso você não tenha se
                identificado nos cupons de compra, abra nosso aplicativo ou site e vincule seus pontos através da
                leitura do QR Code do seu cupom.</p>


            <p>Você acumula nos produtos identificados e em nossas campanhas exclusivas.</p>

            <p>Venha acumular Seeds, aproveite!</p>
        </div>
    </div>

    <!--MODAL-->
    <div id="modal-policy">
        <div class="modal-inner-content" id="content-policy">

        </div>
    </div>

</form>

<script type="text/x-magento-init">
    {
       "*": {
           "passwordValidate": {}
       }
   }
</script>
<script type="text/x-magento-init">
    {
       "*": {
           "passwordValidate2": {}
       }
   }
</script>
<script type="text/x-magento-init">
    {
       "*": {
           "passwordValidate3": {}
       }
   }
</script>
<script type="text/x-magento-init">
    {
       "*": {
           "passwordValidate4": {}
       }
   }
</script>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal',
        'moment',
        'redirectUrl',
        'mage/mage',
        'mage/calendar',
        'jquery.mask',
        'loader'

    ], function($, modal, moment) {

        $("#button_create").prop('disabled', true);

        $("#change_policy").click(function() {
            if ($("#policy_accepted").val() == 0) {
                $("#policy_accepted").val(1);
                if ($("#aceito_termos_uso").prop("checked") == false) {
                    $("#button_create").prop('disabled', false);
                }
            } else {
                $("#policy_accepted").val(0);
                $("#button_create").prop('disabled', true);
            }
            console.log($("#policy_accepted").val());
        });

        $("#toggle").click(function() {

            if ($("#password").attr("type") == "password") {
                //Change type attribute
                $("#password").attr("type", "text");
            } else {
                //Change type attribute
                $("#password").attr("type", "password");
            }
        });

        $("#toggle2").click(function() {

            if ($("#password-confirmation").attr("type") == "password") {
                //Change type attribute
                $("#password-confirmation").attr("type", "text");
            } else {
                //Change type attribute
                $("#password-confirmation").attr("type", "password");
            }
        });

        if ($("#button_create").click(function() {

                if ($('#form-validate').valid()) {
                    var fim = $(".counteudo").loader({
                        texts: {
                            loaderText: 'Falta pouco...\nEstamos processando o seu cadastro',
                            imgAlt: 'Falta pouco...\nEstamos processando o seu cadastro'
                        },
                        template: `<div class="loading-mask" data-role="loader">
												<div class="loader">
														<img alt="<%- data.texts.imgAlt %>" src="<%- data.icon %>">
														<p><%- data.texts.loaderText %></p>
												</div>
										</div>`
                    });
                    fim.loader('show');
                }
            }))

        function checkTerms() {
            if ($("#aceito_termos_uso").prop("checked") == true && $("#aceito_regulamento").prop("checked") ==
                true && $("#policy_accepted").val() == 1) {
                $("#user_fidelidade").val("1");

                $("#button_create").prop('disabled', false);
            } else {
                $("#user_fidelidade").val("0");
                $("#button_create").prop('disabled', true);
            }
        }

        $("#aceito_termos_uso").click(function() {
            checkTerms()
        });
        $("#aceito_regulamento").click(function() {
            checkTerms()
        });


        $("#box").hide();

        $("#is_fidelidade").change(function() {

            if ($("#policy_accepted").val() == 1) {
                $("#button_create").prop('disabled', function(i, v) {
                    return !v;
                });
                $("#box").toggle();
            }

        })

        $("#selecionar_todos").click(function() {
            if ($("#selecionar_todos").prop("checked") == true) {
                $("#aceito_termos_uso").prop("checked", true);
                $("#aceito_regulamento").prop("checked", true);
                $("#desejo_notificacao").prop("checked", true);
                checkTerms();
            } else {
                $("#aceito_termos_uso").prop("checked", false);
                $("#aceito_regulamento").prop("checked", false);
                $("#desejo_notificacao").prop("checked", false);
                checkTerms();
            }
        })

        var options = {
            onKeyPress: function(cpf, ev, el, op) {
                var masks = ["000.000.000-00", "00.000.000/0000-00"];
                $("#cpf").mask(masks[0], op);
            },
        };

        $("#cpf").mask("000.000.000-00", options);

        $("#telephone").mask("(00) 00000-0000");
        $("#telephone2").mask("(00) 0000-0000");
        $("#dob").mask("00/00/0000");

        $('#dob').calendar({
            dateFormat: "dd/mm/yy",
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            currentText: 'Ir para hoje',
            closeText: 'Fechar',
            showWeek: false,
            weekHeader: "Sem",
            yearRange: "-100:+0", // last hundred years
            dayNamesMin: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab"],
            monthNamesShort: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"]
        });

        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            title: 'CPF CADASTRADO',
            buttons: [{
                    text: $.mage.__('ACESSAR A LOJA'),
                    class: 'modal-close',
                    click: function() {
                        var cpf = $("#cpf").val();
                        window.location.href = `/customer/account/login?cpf=${cpf}`;
                    }
                },
                {
                    text: $.mage.__('CRIAR NOVA CONTA'),
                    class: 'modal-login',
                    click: function() {
                        window.location.href = `/customer/account/create`;
                    }
                }
            ]
        };

        var options2 = {
            innerScroll: true,
            type: 'popup',
            responsive: true,
            title: 'O QUE É O C.VALE FIDELIDADE?',
            buttons: []
        };
        var options3 = {
            innerScroll: true,
            type: 'popup',
            responsive: true,
            title: 'Termos de Uso',
        };
        var options4 = {
            innerScroll: true,
            type: 'popup',
            responsive: true,
            title: 'Regulamento do programa de fidelidade',
        };
        var options5 = {
            innerScroll: true,
            type: 'popup',
            responsive: true,
            title: 'O que é o C.Vale fidelidade?',
        };

        modal(options, $('#modal-content'));
        modal(options2, $('#modal-conheca'));

        modal(options3, $('#modal-termos'));
        modal(options4, $('#modal-regulamentos'));
        modal(options5, $('#modal-policy'));



        $("#conheca").click(function() {
            $("#modal-conheca").modal("openModal");
        })

        $("#tu").click(async function() {
            var body = $('body').loader();
            body.loader('show');
            regras = await $.ajax({
                url: "/autentica/germini/regras",
                type: "GET"
            });

            $("#conteuto-termos").html(regras.useTerms);
            $("#modal-termos").modal("openModal");
            body.loader('hide');
        })
        $("#reg").click(async function() {
            var body = $('body').loader();
            body.loader('show');
            regulamentos = await $.ajax({
                url: "/autentica/germini/regulamentos",
                type: "GET"
            });

            $("#conteuto-termos").html(regulamentos.regulation);
            $("#modal-termos").modal("openModal");
            body.loader('hide');
        })

        $("#policy").click(async function() {
            var body = $('body').loader();
            body.loader('show');
            policy = await $.ajax({
                url: "/autentica/germini/policy",
                type: "GET"
            });

            $("#content-policy").html(policy.policy);
            $("#modal-policy").modal("openModal");
            body.loader('hide');
        })

        $("#postcode").blur(async function() {
            try {
                var body = $('body').loader();
                body.loader('show');
                address = await $.ajax({
                    url: "/autentica/germini/endereco",
                    type: "POST",
                    data: {
                        postcode: $("#postcode").val(),
                    }
                });

                $("#region_id").val(address.state);

                if (address.city != null) {
                    cities = await $.ajax({
                        url: "/autentica/germini/cities",
                        type: "POST",
                        data: {
                            region_id: $("#region_id").val(),
                            country: $("#country").val()
                        }
                    });
                    document.getElementById("city").options.length = 0;
                    cities.forEach((city) => {
                        $('#city').append(`<option value="${city.name}">${city.name}</option>`);
                    });

                    $(`#city option[value="${address.city}"]`).attr('selected', 'selected');

                    $("#street_1").val(address.location);
                    $("#street_2").val(address.number);
                    $("#street_3").val(address.district);
                }
            } catch (err) {
                console.error(err.message);
            } finally {
                body.loader('hide');
            }
        });

        $("#cpf").blur(async function() {
            if ($("#cpf").val().length >= 14) {
                var body = $('body').loader();
                body.loader('show');
                $("#cpf_modal").text($("#cpf").val());
                result = await $.ajax({
                    url: "/autentica/germini/recebe",
                    type: "POST",
                    data: {
                        cpf: $("#cpf").val(),
                    },
                });

                console.log(result);

                body.loader('hide');

                // Já existe no Germini
                if (result == true) {
                    $("#modal-content").modal("openModal");
                    $("#button_create").prop('disabled', true);
                } else if (result?.data != null) {
                    $("#button_create").prop('disabled', false);
                    // Usa os dados retornados para preencher campos do formulario
                    // nesse caso, tenho que setar em CreateUpdateConsumer
                    // "associated": true

                    $("#cpf").attr('readonly', 'readonly')

                    $("#cpf").css({
                        backgroundColor: '#dbdbdb'
                    });


                    $("#associated").val("1");
                    let fullName = result?.data?.name;
                    $("#firstname").val(fullName);
                    $("#firstname").attr('readonly', 'readonly')

                    $("#firstname").css({
                        backgroundColor: '#dbdbdb'
                    });

                    let lastName = result?.data?.name;
                    $("#lastname").val(fullName);
                    $("#lastname").attr('readonly', 'readonly')
                    $("#lastname").css({
                        backgroundColor: '#dbdbdb'
                    });
                    let dob = moment(result?.data?.dateOfBirth).format('L');


                    // // $("#dob").val(dob);
                    $("#dob").prop('disabled', 'true')
                    $("#dob").css({
                        backgroundColor: '#dbdbdb'
                    });


                    let gender = result?.data?.gender;
                    let gender_val = 0;
                    switch (gender) {
                        case "M":
                            gender_val = 1;
                            break;
                        case "F":
                            gender_val = 2;
                            break;
                        default:
                            gender_val = 3;
                            break;
                    }
                    $("#gender").val(gender_val);
                    $("#gender").attr('readonly', 'readonly')
                    $("#gender").css({
                        backgroundColor: '#dbdbdb'
                    });
                    $('#gender option:not(:selected)').attr('disabled', true);



                    let email = result?.data?.email;
                    $("#email_address").val(email);
                    let telephone = result?.data?.phoneNumber2;
                    $("#telephone").val(telephone);
                    let telephone2 = result?.data?.phoneNumber;
                    $("#telephone2").val(telephone2);
                    let postcode = result?.data?.address?.zipCode;
                    console.log(postcode)
                    $("#postcode").val(postcode);
                    $("#postcode").attr('readonly', 'readonly')
                    $("#postcode").css({
                        backgroundColor: '#dbdbdb'
                    });
                    $("#postcode").removeClass();
                    $("#postcode").removeAttr("aria-required")
                    $("#postcode").removeAttr("maxlength")
                    $("#postcode").attr('readonly', 'readonly')


                    let street_1 = result?.data?.address?.location;
                    $("#street_1").val(street_1);
                    $("#street_1").attr('readonly', 'readonly')
                    $("#street_1").css({
                        backgroundColor: '#dbdbdb'
                    });
                    let street_2 = result?.data?.address?.number;
                    $("#street_2").val(street_2);
                    $("#street_2").attr('readonly', 'readonly')
                    $("#street_2").css({
                        backgroundColor: '#dbdbdb'
                    });
                    let street_3 = result?.data?.address?.district;
                    $("#street_3").val(street_3);
                    $("#street_3").attr('readonly', 'readonly')
                    $("#street_3").attr('type', 'password')
                    $("#street_3").css({
                        backgroundColor: '#dbdbdb'
                    });
                    let complemento = result?.data?.address?.aditionalInfo;
                    $("#complemento").val(complemento);
                    $("#complemento").attr('readonly', 'readonly')
                    $("#complemento").css({
                        backgroundColor: '#dbdbdb'
                    });

                    let estate = result?.data?.address?.state?.name;
                    $("#region_id").attr('readonly', 'readonly')
                    $("#region_id").css({
                        backgroundColor: '#dbdbdb'
                    });
                    var x = new Option(estate, estate);
                    /// jquerify the DOM object 'o' so we can use the html method
                    $(x).html(estate);
                    $("#region_id").append(x);
                    $("#region_id").val(estate).change();



                    let city = result?.data?.address?.city?.name;
                    $("#city").attr('readonly', 'readonly')
                    $("#city").css({
                        backgroundColor: '#dbdbdb'
                    });
                    var o = new Option(city, city);
                    /// jquerify the DOM object 'o' so we can use the html method
                    $(o).html(city);
                    $("#city").append(o);
                    $("#city").val(city).change();



                    $("#country").attr('readonly', 'readonly')
                    $("#country").css({
                        backgroundColor: '#dbdbdb'
                    });


                }


            }
        });

        $("#region_id").change(async function() {
            if ($("#associated").val() == 0) {
                var body = $('body').loader();
                body.loader('show');
                result = await $.ajax({
                    url: "/autentica/germini/cities",
                    type: "POST",
                    data: {
                        region_id: $("#region_id").val(),
                        country: $("#country").val()
                    }
                });
                console.log(result);
                document.getElementById("city").options.length = 0;
                result.forEach((city) => {
                    $('#city').append(`<option value="${city.name}">${city.name}</option>`);
                })
                body.loader('hide');
            }
        })

        var dataForm = $('#form-validate');

    });
</script>

<?php if (true) : ?>

    <script type="text/x-magento-init">
        {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo ($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#postcode",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php endif; ?>
