<style>
    .cart-footer .cart-qty {
        display: none;
    }

    #policy {
        cursor: pointer;
        color: #21409A;
        font-style: normal;
        text-decoration: underline;
    }

    .search {
        position: relative;
        color: #aaa;
        font-size: 16px;
    }

    .search {}

    .search input {}

    .search input {}

    .search .fa-search {
        position: absolute;
        left: 10px;
        top: 5px;
    }

    .search .fa-search {
        left: auto;
        right: 10px;
    }


    .input-icons {
        width: 100%;
        margin-bottom: 10px;
    }

    .icon {
        padding: 10px;

    }

    .input-field {
        width: 100%;
        padding: 10px;
        padding-right: 50px;
        text-align: left;
    }

    .loading-mask .loader>p {
        display: block;
        font-size: large;
    }

    .nav-sections {
        margin-bottom: 0px !important;
    }

    .vl {
        border-left: 2px solid #444444;
        height: 100%;
        margin-right: 20px;
    }

    a {
        color: #21409A;
    }

    .modal-inner-content {
        line-height: 20px;
    }

    ul>li,
    ol>li {
        margin-top: 0rem;
        margin-bottom: 0px !important;
    }

    :root {
        --num-of-grid-columns: 6;
    }

    form {
        width: 100% !important;
    }

    .counteudo {
        display: grid;
        background: #f8f8f8 !important;
        grid-template-columns: repeat(var(--num-of-grid-columns), 1fr);
        grid-gap: 20px;
        grid-template-areas:
            "cpf_field nome1 nome2 nome2 nasc genero"
            "email email email email celular telefone"
            "cep endereco endereco endereco numero complemento"
            "bairro cidade uf pais . ."
            "senha senha conf_senha conf_senha . ."
    }

    @media screen and (max-width: 768px) {
        :root {
            --num-of-grid-columns: 1;
        }

        .counteudo {
            display: grid;
            background: #f8f8f8 !important;
            grid-template-columns: repeat(var(--num-of-grid-columns), 1fr);
            grid-gap: 30px;
            grid-template-areas: "cpf_field"
                "nome1"
                "nome2"
                "nasc"
                "genero"
                "email"
                "celular"
                "telefone"
                "cep"
                "endereco"
                "numero"
                "complemento"
                "bairro"
                "cidade"
                "uf"
                "pais"
                "senha"
                "conf_senha"
        }
    }

    #cpf_field {
        grid-area: cpf_field;
    }

    #firstname_field {
        grid-area: nome1;
    }

    #lastname_field {
        grid-area: nome2;
    }

    #nasc_field {
        grid-area: nasc;
    }

    #gender_field {
        grid-area: genero;
    }

    #email_field {
        grid-area: email;
    }

    #phone_field {
        grid-area: celular;
    }

    #phone_field2 {
        grid-area: telefone;
    }

    #zip_field {
        grid-area: cep;
    }

    #address_field {
        grid-area: endereco;
    }

    #number_field {
        grid-area: numero;
    }

    #complement_field {
        grid-area: complemento;
    }

    #bairro_field {
        grid-area: bairro;
    }


    #city_field {
        grid-area: cidade;
    }

    #uf_field {
        grid-area: uf;
    }

    #pais_field {
        grid-area: pais;
    }

    #password_field {
        grid-area: senha;
    }

    #password_field2 {
        grid-area: conf_senha;
    }

    .label {
        width: auto !important;
    }

    .modal-inner-wrap {
        border-radius: 8px;
    }

    #box {
        padding: 20px;
        background: #fff;
        border-radius: 10px;
        margin-top: 20px;
        height: 100px;
        display: flex;
        width: 800px;
    }

    #left {
        height: 100%;
        width: 30%;
        display: flex;
        justify-content: left;
        align-items: center;
        font-weight: bold;
    }

    #right {
        height: 100%;
        width: 70%;
        display: flex;
        justify-content: center;
        align-items: start;
        flex-direction: column;
    }

    .loading-mask-custom2 {
        position: absolute;
        top: 50%;
        left: 50%;
        background: rgba(0, 0, 0, 0.6);
        z-index: 2;
        width: 600px;
        transform: translate(-50%, -50%);
        height: 200px;
        color: #fff;
        font-size: large;
        border-radius: 20px;
    }

    .tooltip {
        display: inline-block;
        position: relative;
        text-align: left;
    }

    .tooltip h3 {
        margin: 12px 0;
    }

    .tooltip .top {
        min-width: 300px;
        max-width: 400px;
        top: -20px;
        left: 50%;
        transform: translate(-30%, -100%);
        padding: 10px 20px;
        color: #ffffff;
        background-color: #444444;
        font-weight: normal;
        font-size: 14px;
        border-radius: 8px;
        position: absolute;
        z-index: 99999999;
        box-sizing: border-box;
        box-shadow: 0 1px 8px rgba(0, 0, 0, 0.5);
        display: none;
    }

    .tooltip:hover .top {
        display: block;
    }

    .tooltip .top i {
        position: absolute;
        top: 100%;
        left: 30%;
        margin-left: -15px;
        width: 30px;
        height: 15px;
        overflow: hidden;
    }

    .tooltip .top i::after {
        content: '';
        position: absolute;
        width: 15px;
        height: 15px;
        left: 50%;
        transform: translate(-50%, -50%) rotate(45deg);
        background-color: #444444;
        box-shadow: 0 1px 8px rgba(0, 0, 0, 0.5);
    }



    .tooltip h3 {
        margin: 12px 0;
    }


    .tooltip .text-content {
        padding: 10px 20px;
    }

    .tooltip .right {
        min-width: 350px;
        max-width: 400px;
        top: 50%;
        left: 100%;
        margin-left: 20px;
        transform: translate(0, -50%);
        padding: 0;
        color: #EEEEEE;
        background-color: #444444;
        font-weight: normal;
        font-size: 13px;
        border-radius: 8px;
        position: absolute;
        z-index: 99999999;
        box-sizing: border-box;
        box-shadow: 0 1px 8px rgba(0, 0, 0, 0.5);
        visibility: hidden;
        opacity: 0;
        transition: opacity 0.8s;
    }

    .tooltip:hover .right {
        visibility: visible;
        opacity: 1;
    }

    .tooltip .right img {
        width: 400px;
        border-radius: 8px 8px 0 0;
    }

    .tooltip .text-content {
        padding: 10px 20px;
    }

    .tooltip .right i {
        position: absolute;
        top: 50%;
        right: 100%;
        margin-top: -12px;
        width: 12px;
        height: 24px;
        overflow: hidden;
    }

    .tooltip .right i::after {
        content: '';
        position: absolute;
        width: 12px;
        height: 12px;
        left: 0;
        top: 50%;
        transform: translate(50%, -50%) rotate(-45deg);
        background-color: #444444;
        box-shadow: 0 1px 8px rgba(0, 0, 0, 0.5);
    }
</style>


<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Resetpassword $block */
?>
<form action="<?= $block->escapeUrl($block->getUrl('*/*/resetpasswordpost', ['_query' => ['token' => $block->getResetPasswordLinkToken()]])) ?>" method="post" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off" <?php endif; ?> id="form-validate" class="form password reset" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <!-- <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
            <label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
            <div class="control">

                <input type="password" class="input-text" name="password" id="password" data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>" data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>" data-validate="{required:true, 'validate-customer-password':true}" autocomplete="off">
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div>
            </div>
        </div> -->
        <div id="password_field">
            <div class="field fieldset individual">
                <div class="field required">
                    <label for="password" class="label">Senha</label>

                    <div class="search">
                        <img style="height: 30px;" class="fa fa-search" id="toggle" src="<?php echo $this->getViewFileUrl('Vexpro_Autenticacao::img/eye-solid.png'); ?>" />
                        <input maxlength="20" data-validate="{required:true, germiniPassword:true, germiniPassword2:true,germiniPassword3:true,germiniPassword4:true}" type="password" name="password" validate-password id="password" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" class="input-text" autocomplete="off">
                    </div>

                </div>
            </div>
        </div>

        <div id="password_field2">
            <div class="field fieldset individual">
                <div class="field required">
                    <label for="password-confirmation" class="label">Confirmar senha</label>

                    <div class="search">
                        <img style="height: 30px;" class="fa fa-search" id="toggle2" src="<?php echo $this->getViewFileUrl('Vexpro_Autenticacao::img/eye-solid.png'); ?>" />
                        <input maxlength="20" type="password" name="password_confirmation" title="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                    </div>


                    <div style="float: left; margin-top: 5px; display: flex; align-items: center;">
                        <span style="color: #7E7E7E; margin-right: 15px">Políticas de senha</span>
                        <div class="tooltip">
                            <img style="margin-right: 20px" src="<?php echo $this->getViewFileUrl('Vexpro_Autenticacao::img/info-circle-solid.png'); ?>" />
                            <div class="right" style="padding-top: 5px; ">
                                <span style="font-weight: bold; margin-left: 15px; margin-top: 15px; font-size: 12px;">Regras:</span>
                                <ul style="margin-left: -15px;">
                                    <li>No mínimo 8 caracteres</li>
                                    <li>Conter letras, números e caracteres especiais</li>
                                    <li>Não pode ter mais de 3 números sequenciais</li>
                                    <li>Não pode ter números repetidos em ordem</li>
                                    <li>Não ser igual ao CPF, CNPJ, data de nascimento, telefone ou celular.</li>
                                </ul>
                                <i></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Set a New Password')) ?></span></button>
        </div>
    </div>
</form>

<script type="text/x-magento-init">
    {
       "*": {
           "passwordValidate": {}
       }
   }
</script>
<script type="text/x-magento-init">
    {
       "*": {
           "passwordValidate2": {}
       }
   }
</script>
<script type="text/x-magento-init">
    {
       "*": {
           "passwordValidate3": {}
       }
   }
</script>
<script type="text/x-magento-init">
    {
       "*": {
           "passwordValidate4": {}
       }
   }
</script>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal',
        'moment',
        'redirectUrl',
        'mage/mage',
        'mage/calendar',
        'jquery.mask',
        'loader'

    ], function($, modal, moment) {
        $("#toggle").click(function() {

            if ($("#password").attr("type") == "password") {
                //Change type attribute
                $("#password").attr("type", "text");
            } else {
                //Change type attribute
                $("#password").attr("type", "password");
            }
        });

        $("#toggle2").click(function() {

            if ($("#password-confirmation").attr("type") == "password") {
                //Change type attribute
                $("#password-confirmation").attr("type", "text");
            } else {
                //Change type attribute
                $("#password-confirmation").attr("type", "password");
            }
        });
    });
</script>
